### ISSUE TITLE
Runtime error on OpenJDK 10

### ISSUE THREAD

**Issue by jhidding** [openstreetmap/osmembrane#11]
Hi, running the latest available JAR file (version 1.1.0) I get a runtime error:
```
$ java -jar OSMembrane.jar
libpng warning: iCCP: known incorrect sRGB profile
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3090)
	at java.base/java.lang.Class.getConstructor0(Class.java:3295)
	at java.base/java.lang.Class.newInstance(Class.java:532)
	at de.osmembrane.model.persistence.PersistenceFactory.getPersistence(PersistenceFactory.java:63)
	at de.osmembrane.model.pipeline.FunctionPrototype.initiate(FunctionPrototype.java:62)
	at de.osmembrane.Application.createModels(Application.java:120)
	at de.osmembrane.Main.main(Main.java:42)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 8 more
```

```
$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)
```

**Comment by foxylion** [comment]
This should be fixed in [v1.2.0](https://github.com/openstreetmap/osmembrane/releases/tag/v1.2.0)
