### ISSUE TITLE
EC parameters error on running make build

### ISSUE THREAD

**Issue by jeremy-rutman** [openstreetmap/osmembrane#17]
Hi , I ran into trouble running make build (apologies if this is some obvious java error, I have little experience with java): 

```
jeremyr@dap-jupyter01:~/osm/osmembrane$ sudo make build
./gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.8-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1896)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1854)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1837)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1358)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1335)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1366)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
	at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
	at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
	at java.util.ArrayList.indexOf(ArrayList.java:303)
	at java.util.ArrayList.contains(ArrayList.java:286)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1584)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:220)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:972)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:901)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1025)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1324)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1351)
	... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
	at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
	at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
	at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
	... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.Security.getImpl(Security.java:697)
	at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
	at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
	... 30 more
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by foxylion** [comment]
Hey @jeremy-rutman ,
which version of Java do you use? You can find out by executing `java -version`.

**Comment by foxylion** [comment]
Also please know that you are not required to build the application.
You can download a pre-built jar from https://github.com/openstreetmap/osmembrane/releases

**Comment by jeremy-rutman** [comment]
I was on java 1.7.x, upgraded to java 1.8.0_201 and ran `java -jar OSMembrane.jar` which seems to have done the trick - thanks !!!
